### ISSUE TITLE
problem with loop

### ISSUE THREAD

**Issue by Mohaddaseh** [CoffeeMIPS/netbeans#1]
this code is not working : 

addi $a1,$zero,0
addi $a2,$zero,0
cm:
addi $a1,$a1,1
bne  $a1,$a2,cm

i mean if we want to jump to the previews code it doesn't understand using bne or beq 
only jump (j) work so we have to write it in this way :

addi $a1,$zero,0
addi $a2,$zero,0
addi $a2,$a2,10
fr:
addi $a1,$a1,1
bne  $a1,$a2,cm
j end1
cm:
j fr
end1:

**Comment by barooni** [comment]
thanks for report ...
yes it was a bug and it fixed now ...

**Comment by Mohaddaseh** [comment]
Your welcome :)
